### ISSUE TITLE
does not build

### ISSUE THREAD

**Issue by LeeBreisacher** [greenscreens-io/jt400-extra#1]
I cloned the repo and typed "mvn clean install" and I get compile errors:
jt400-extra/io.greenscreens.jt400/src/main/java/io/greenscreens/jt400/JT400ExtFormatBuilder.java:[295,46] method slice in class java.nio.ByteBuffer cannot be applied to given types;
[ERROR]   required: no arguments
[ERROR]   found: int,int
[ERROR]   reason: actual and formal argument lists differ in length

It looks like the code depends on java 11?, but the pom has source level 1.8.  

Hm, doesn't seem to be 11 either. Please advise..

Ah, I downloaded jdk15 and that seems to work.

**Comment by greenscreens-io** [comment]
Hi @LeeBreisacher ,

Thx for the info. It is fixed now to support Java 8 compile.
