### ISSUE TITLE
DEVD0600.jobNumber is 6 bytes, not 10

### ISSUE THREAD

**Issue by LeeBreisacher** [greenscreens-io/jt400-extra#2]
In DEVD0600, the jobNumber field is 6 bytes, not 10:

	@JT400Format(offset = 912, length = 10)
	protected String jobNumber;

See https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/apis/QDCRDEVD.htm.

**Comment by greenscreens-io** [comment]
Hi @LeeBreisacher 

Thx, fixed!
