### ISSUE TITLE
support for UserSpace and List APIs

### ISSUE THREAD

**Issue by LeeBreisacher** [greenscreens-io/jt400-extra#3]
Hi. This is not a bug report, just a question/comment. I wasn't sure how to contact you another way. 

I'm working on the List Objects (QUSLOBJ) API. It uses a UserSpace to hold the result of the call. So, before the actual call to the host, I need to create the UserSpace, e.g. 

        String USERSPACE_PATH = "/QSYS.LIB/QTEMP.LIB/SPC.USRSPC";
        UserSpace us = new UserSpace(as400, USERSPACE_PATH);
        us.setMustUseProgramCall(true);
        us.create(140, true, " ", (byte)0, "", "*ALL");

and then after the call, read the contents, e.g. 

        byte[] bytes = new byte[140];
        us.read(bytes, 0, 0, 140);

I can of course do all this outside of the "QUSLOBJ implements IJT400Params" class, but I'm wondering if the basic invoke/call mechanism could include generic "pre-call" and "post-call" callbacks/lambdas. 

In addition, it might be nice to have IJT400Format classes that represents the generic header formats described here:  https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/apiref/usfcommonstructure.htm

WDYT?

**Comment by greenscreens-io** [comment]
Hi,

Can you please elaborate a little bit more your use-case for pre-call, post-call callbacks?
This lib is a wrapper for JT400 ProgrammCall and ServiceCall to simplify data structures mapping.

...

There are hundreds of structures, it would take a lot of time to map them all.
That's the user community here to help out. :) 

Lib is intended to be generic as possible to support many variations. Hovewer, it is 
quite easy to map any of IBM defined data structures. Please refer to src/test examples.

To decode generic user space structure to Java class, you can create data class definition like this...

```
@Id(value = 0)
@JT400Format(length = 192)  // last offset (150) + last offset length (42)
public class GENHDR0100 implements IJT400Format {

	@JT400Format(offset = 0, length = 64, type = AS400DataType.TYPE_TEXT)
	protected String userArea;

	@JT400Format(offset = 64, type = AS400DataType.TYPE_BIN4)	
	protected int genericHeaderSize;
	
	.... and so on, follow structure offsets and data types from
	https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/apiref/usfcommonstructure.htm  
}
```

Then convert byte array data received from user space with one liner...

```
    byte[] bytes = new byte[140];
    us.read(bytes, 0, 0, 140);
	
    final GENHDR0100 result = JT400ExtFactory.build(as400, GENHDR0100.class, ByteBuffer.wrap(bytes));
```
	
If you need format 0300 also, extend GENHDR0100 like 

```
@Id(value = 0)
@JT400Format(length = 576)  // last offset 448 + length of 128
public class GENHDR0300 extends GENHDR0100 {
	
	// 192	C0	CHAR(256)	API entry point name
	@JT400Format(offset = 192, length = 256, type = AS400DataType.TYPE_TEXT)
	protected String apiEntryPointName;

	// 448	1C0	CHAR(128)	Reserved
	@JT400Format(offset = 448, length = 128, type = AS400DataType.TYPE_TEXT)
	protected String reserved;
	
}
```

**Comment by LeeBreisacher** [comment]
Yeah, after I wrote this issue, I figured out exactly what you've shown here. Good to know I'm doing it right (and it's working fine). 
Regarding the pre-call/post-call, I was thinking it might be necessary to run some code just before the actual call and just after the call, but after tinkering today, it works fine as-is. Thanks.
